modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "pokemeteors"
version = "${version}"
displayName = "Pokémeteors"
authors = "Emafire003"
description = '''
Spawn space-adjacent (or not!) pokémons inside OhMyMeteor's meteors that fall down to the overworld!
'''
logoFile = "assets/pokemeteors/icon.png"

[[dependencies.pokemeteors]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokemeteors]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pokemeteors]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.pokemeteors]]
modId = "ohmymeteors"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "AFTER"
side = "BOTH"

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="${mod_id}.mixins.json"
